/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description genereate API key for gRPC endpoints */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API generated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            "api-key": string;
                        };
                    };
                };
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description check if user is authorized */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            authorized: boolean;
                        };
                    };
                };
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            authorized: boolean;
                        };
                    };
                };
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve all experiment with a list of their runs. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successfully retrieved experiments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExperimentsResponse"];
                    };
                };
                /** @description could not retrieve experiments */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exp/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve runs and metrics linked to an experiment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id of the experiment */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description retrieved experiment successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExperimentResponse"];
                    };
                };
                /** @description could not find experiment runs */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not retrieve experiment data */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exp/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve metrics linked to an experiment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id of the experiment */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description retrieved metrics successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExperimentMetricsResponse"];
                    };
                };
                /** @description could not retrieve metrics */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exp/{id}/metric/{mid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a metric from an experiment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id of the experiment */
                    id: string;
                    /** @description id of the metric */
                    mid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description retrieved metric successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExperimentMetricResponse"];
                    };
                };
                /** @description could not find metrics */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not retrieve metric */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exp/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve all artifact ids for each run in the experiment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id of the experiment */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description retrieved artifacts successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExperimentArtifactsResponse"];
                    };
                };
                /** @description could not find resource */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not retrieve artifacts */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifact/{rid}/{aid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve an artifact with a runId and an artifactId */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id of the run */
                    rid: string;
                    /** @description id of the artifact */
                    aid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description requested artifact file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description could not find resource */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not retrieve resource */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve all registry names */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description retrieved registries successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegistriesResponse"];
                    };
                };
                /** @description could not retrieve resource */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description create a new model registry */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRegistryRequest"];
                };
            };
            responses: {
                /** @description model registry created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateRegistryResponse"];
                    };
                };
                /** @description could not create model registry due to bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not retrieve resource */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve a model registry */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id of the model registry */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description retrieved model registry successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegistryResponse"];
                    };
                };
                /** @description could not find resource */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not retrieve resource */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve list of benchmarks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description retrieved benchmarks successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BenchmarksResponse"];
                    };
                };
                /** @description could not retrieve artifacts */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description create a new benchmark */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBenchmarkRequest"];
                };
            };
            responses: {
                /** @description benchmark created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateBenchmarkResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benchmark/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description get benchmark by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description benchmark id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description retrieved benchmark successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BenchmarkResponse"];
                    };
                };
                /** @description could not find benchmark */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not retrieve benchmark */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** @description delete benchmark */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description benchmark id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description benchmark deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteBenchmarkResponse"];
                    };
                };
                /** @description could not delete benchmark */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description method not implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description update benchmark */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description benchmark id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBenchmarkRequest"];
                };
            };
            responses: {
                /** @description benchmark updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateBenchmarkResponse"];
                    };
                };
                /** @description bad benchmark update request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not find benchmark */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not update benchmark */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/benchmark/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description toggle benchmark pause/unpause */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description benchmark id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description benchmark toggled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BenchmarkToggleResponse"];
                    };
                };
                /** @description bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description benchmark not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not toggle benchmark */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benchmark/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve all benchmark runs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description benchmark id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description benchmark runs retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BenchmarkRunsResponse"];
                    };
                };
                /** @description could not find benchmark */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description could not fetch benchmark runs */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/benchmark/{id}/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description retrieve best benchmark runs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description benchmark id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BestBenchmarkRequest"];
                };
            };
            responses: {
                /** @description best benchmark retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BestBenchmarkResponse"];
                    };
                };
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRegistryRequest: {
            name?: string;
            benchmarkImage?: string;
            benchmarkGpuPassthrough?: boolean;
        };
        CreateBenchmarkRequest: {
            /** @description Name of the benchmark */
            name: string;
            /** @description Whether to start immediately */
            eagerStart?: boolean;
            /** @description Automatically tag the benchmark */
            autoTag?: boolean;
            /** @description Custom tag (if autoTag is true) */
            tag?: string;
            /** @description Metric used for decision making */
            decisionMetric?: string;
            /** @description List of registry names or IDs */
            registries: string[];
            /** @description List of benchmark metrics */
            metrics: components["schemas"]["BenchMetric"][];
            /** @description Name of the dataset */
            datasetName: string;
            /**
             * Format: uri
             * @description URL to the dataset
             */
            datasetURL: string;
            /** @description Whether dataset is stored in S3 */
            datasetFromS3: boolean;
        };
        UpdateBenchmarkRequest: {
            /** @description New name for the benchmark */
            name?: string;
            /** @description Update autotag setting – can be true, false, or null (to clear) */
            autoTag?: boolean | null;
            /** @description Update the custom tag */
            tag?: string;
            /** @description Update the decision metric */
            decisionMetric?: string;
        };
        /** @description benchmark metrics */
        BestBenchmarkRequest: string[];
        ExperimentsResponse: {
            /** @description description of successful operation */
            details: string;
            /**
             * @description Map of experiment ids to list of recorded run ids.
             * @example {
             *       "exp1": [
             *         "run#1",
             *         "run#2"
             *       ],
             *       "exp2": [
             *         "run#3"
             *       ]
             *     }
             */
            exps: {
                [key: string]: string[];
            };
        };
        ExperimentResponse: {
            /** @description description of successfully operation */
            details: string;
            /** @description array of object with run information */
            runs: components["schemas"]["RunInfo"][];
            /** @description array of all run ids linked to the experiment. */
            metrics: string[];
        };
        ExperimentMetricsResponse: {
            /** @description description of successfully operation */
            details: string;
            /** @description array of all run ids linked to the experiment. */
            metrics: string[];
        };
        ExperimentMetricResponse: {
            /** @description description of successfully operation */
            details: string;
            /** @enum {string} */
            kind: "metric/continuous" | "metric/multival" | "metric/single-numeric" | "metric/single" | "metric/complex";
            /**
             * @description Map of run id to list of metric vals
             * @example {
             *       "run1": [
             *         1,
             *         23,
             *         342,
             *         454
             *       ],
             *       "run2": [
             *         "34",
             *         "23",
             *         342,
             *         454
             *       ],
             *       "run3": [],
             *       "run4": [
             *         "/path/to/smth"
             *       ]
             *     }
             */
            metric: {
                [key: string]: unknown[];
            };
        };
        ExperimentArtifactsResponse: {
            /** @description description of successful operation */
            details: string;
            /**
             * @description Map of run id to list of artifact ids
             * @example {
             *       "run1": [
             *         "log.txt",
             *         "artifact#1"
             *       ]
             *     }
             */
            artifacts: {
                [key: string]: string[];
            };
        };
        RegistriesResponse: {
            /** @description description of successfully operation */
            details: string;
            registries: string[];
        };
        RegistryResponse: {
            /** @description description of successful operation */
            details: string;
            registry: components["schemas"]["Registry"];
        };
        CreateRegistryResponse: {
            details: string;
            id: string;
        };
        BenchmarksResponse: {
            /** @description description of successfully operation */
            details: string;
            /** @description array of benchmark ids */
            benchmarks: string[];
        };
        CreateBenchmarkResponse: {
            /** @description id of new benchmark */
            id: string;
            /** @description true if benchmark was created */
            created: boolean;
            details: string;
        };
        BenchmarkResponse: {
            benchmark: components["schemas"]["Bench"];
            details: string;
        };
        UpdateBenchmarkResponse: {
            details: string;
        };
        DeleteBenchmarkResponse: {
            details: string;
        };
        BenchmarkToggleResponse: {
            details: string;
        };
        BenchmarkRunsResponse: {
            runs: components["schemas"]["BenchRun"][];
            details: string;
        };
        BestBenchmarkResponse: {
            details: string;
            runs: {
                [key: string]: components["schemas"]["BenchRun"][];
            };
        };
        RunInfo: {
            /** @example run#234 */
            runId: string;
            /** Format: date-time */
            createdAt: string;
            color: string;
        };
        ErrorResponse: {
            /** @description details on why operation was unsuccessful */
            error: string;
        };
        Registry: {
            /** @description Registry details */
            details: string;
            /** @description Registry name */
            name: string;
            /**
             * Format: int64
             * @description Last version number
             */
            lastVer: number;
            /** @description Map of tag names to lists of integer IDs */
            tags: {
                [key: string]: number[];
            };
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            createdAt: string;
            /** @description Map of entry IDs to their information */
            entriesInfo: {
                [key: string]: components["schemas"]["EntryInfo"];
            };
            /** @description docker image for benchmarking */
            benchmarkImage?: string;
            /** @description enable/disable gpu passthrough when benchmarking */
            benchmarkGpuPassthrough?: boolean;
        };
        /** @description model entry information */
        EntryInfo: {
            createdAt?: string;
        };
        Bench: {
            /**
             * @description Unique benchmark identifier
             * @example bench-123
             */
            id: string;
            /**
             * @description Benchmark name
             * @example performance-test-01
             */
            name: string;
            /**
             * @description Whether the benchmark is paused
             * @example false
             */
            paused?: boolean;
            /**
             * @description Whether to start immediately
             * @example true
             */
            eagerStart?: boolean;
            /**
             * @description Automatically assign a tag
             * @example false
             */
            autoTag?: boolean;
            /**
             * @description Custom tag (required)
             * @example nightly-run
             */
            tag: string;
            /**
             * @description Metric used for decision making
             * @example accuracy
             */
            decisionMetric?: string;
            /**
             * @description List of registry names or IDs
             * @example [
             *       "registry-a",
             *       "registry-b"
             *     ]
             */
            registries: string[];
            /** @description List of benchmark metrics */
            metrics: components["schemas"]["BenchMetric"][];
            /**
             * @description Name of the dataset
             * @example cifar10
             */
            datasetName: string;
            /**
             * Format: uri
             * @description URL to the dataset (must be a valid URL)
             * @example https://example.com/datasets/cifar10
             */
            datasetUrl: string;
            /**
             * @description Whether the dataset is stored in S3
             * @example true
             */
            fromS3?: boolean;
            /**
             * Format: date-time
             * @description Creation or last update timestamp
             * @example 2025-05-08T12:34:56Z
             */
            timestamp: string;
        };
        BenchMetric: {
            name: string;
            descSort?: boolean;
        };
        BenchRun: {
            /**
             * @description Registry name or identifier
             * @example registry-main
             */
            registry?: string;
            /**
             * Format: int64
             * @description Version number
             * @example 42
             */
            version?: number;
            /**
             * @description Map of metric names to float32 values
             * @example {
             *       "accuracy": 0.95,
             *       "loss": 0.23
             *     }
             */
            metrics?: {
                [key: string]: number;
            };
            /**
             * Format: date-time
             * @description Run timestamp
             * @example 2025-05-08T14:30:00Z
             */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
